using TogetherBoardsApp.Backend.Application.Abstractions;

namespace TogetherBoardsApp.Backend.Application.UserAccounts.GetCurrentLoggedInUserAccount;

public sealed record GetCurrentLoggedInUserAccountQuery : IQuery<GetCurrentLoggedInUserAccountQueryResponse>;