name: build and test main

on:
  push:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '8.0.101' # The .NET SDK version to use

jobs:
  build-and-test-backend:

    name: build-and-test-backend-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      working-directory: ./Backend
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./Backend

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./Backend